import { Brand, Product, TestResult, Ingredient } from '@/types/database';

// ============================================
// MOCK DATA - Replace with Supabase queries
// ============================================

export const mockBrands: Brand[] = [
    {
        id: '1',
        name: 'Ritual',
        slug: 'ritual',
        logo_url: '/brands/ritual.png',
        affiliate_link: 'https://ritual.com',
        trust_score: 95,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Needed',
        slug: 'needed',
        logo_url: '/brands/needed.png',
        affiliate_link: 'https://needed.com',
        trust_score: 88,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'Seeking Health',
        slug: 'seeking-health',
        logo_url: '/brands/seeking-health.png',
        affiliate_link: 'https://seekinghealth.com',
        trust_score: 72,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        name: 'Garden of Life',
        slug: 'garden-of-life',
        logo_url: '/brands/garden-of-life.png',
        affiliate_link: 'https://gardenoflife.com',
        trust_score: 45,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '5',
        name: 'Clearly Filtered',
        slug: 'clearly-filtered',
        logo_url: '/brands/clearly-filtered.png',
        affiliate_link: 'https://clearlyfiltered.com',
        trust_score: 98,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '6',
        name: 'AquaTru',
        slug: 'aquatru',
        logo_url: '/brands/aquatru.png',
        affiliate_link: 'https://aquatruwater.com',
        trust_score: 96,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '7',
        name: 'Hydroviv',
        slug: 'hydroviv',
        logo_url: '/brands/hydroviv.png',
        affiliate_link: 'https://hydroviv.com',
        trust_score: 92,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const mockIngredients: Ingredient[] = [
    {
        id: '1',
        name: 'Zinc Oxide',
        safety_level: 'Safe',
        description: 'A mineral that provides natural sun protection. Generally recognized as safe by the FDA.',
        sources: ['https://www.fda.gov'],
    },
    {
        id: '2',
        name: 'Vitamin D3',
        safety_level: 'Safe',
        description: 'Essential vitamin for bone health and immune function. Sourced from lichen for vegan products.',
        sources: ['https://ods.od.nih.gov'],
    },
    {
        id: '3',
        name: 'Folate (as L-Methylfolate)',
        safety_level: 'Safe',
        description: 'The bioavailable form of folate. Critical for pregnancy and cell division.',
        sources: ['https://www.ncbi.nlm.nih.gov'],
    },
    {
        id: '4',
        name: 'Fragrance',
        safety_level: 'Avoid',
        description: 'Umbrella term that can hide hundreds of undisclosed chemicals, including endocrine disruptors.',
        sources: ['https://www.ewg.org'],
    },
    {
        id: '5',
        name: 'Titanium Dioxide',
        safety_level: 'Caution',
        description: 'Common colorant. Safe topically but concerns exist about nano-particles in supplements for ingestion.',
        sources: ['https://www.ewg.org'],
    },
    {
        id: '6',
        name: 'Magnesium Glycinate',
        safety_level: 'Safe',
        description: 'Highly bioavailable form of magnesium. Gentle on the stomach and well-absorbed.',
        sources: ['https://examine.com'],
    },
    {
        id: '7',
        name: 'Activated Carbon',
        safety_level: 'Safe',
        description: 'Absorbs chlorine, VOCs, and improves taste. Standard in most water filters.',
        sources: ['https://www.epa.gov'],
    },
    {
        id: '8',
        name: 'Ion-Exchange Resin',
        safety_level: 'Safe',
        description: 'Used to remove heavy metals and scale-causing minerals.',
        sources: ['https://www.wqa.org'],
    },
];

export const mockTestResults: TestResult[] = [
    {
        id: '1',
        product_id: '1',
        test_type: 'PFAS',
        status: 'NonDetect',
        result_value: '<0.01 ppm',
        pdf_url: '/coa/ritual-pfas-2024.pdf',
        tested_at: '2024-11-15',
        lab_name: 'Eurofins',
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        product_id: '1',
        test_type: 'HeavyMetals',
        status: 'Pass',
        result_value: 'Lead <0.5ppb',
        pdf_url: '/coa/ritual-heavymetals-2024.pdf',
        tested_at: '2024-10-20',
        lab_name: 'Eurofins',
        created_at: new Date().toISOString(),
    },
    {
        id: '3',
        product_id: '1',
        test_type: 'Glyphosate',
        status: 'NonDetect',
        pdf_url: '/coa/ritual-glyphosate-2024.pdf',
        tested_at: '2024-09-10',
        lab_name: 'NSF International',
        created_at: new Date().toISOString(),
    },
    {
        id: '4',
        product_id: '1',
        test_type: 'Pesticides',
        status: 'Pass',
        result_value: 'All Clear',
        tested_at: '2024-08-05',
        lab_name: 'NSF International',
        created_at: new Date().toISOString(),
    },
    {
        id: '5',
        product_id: '1',
        test_type: 'Microplastics',
        status: 'Pending',
        created_at: new Date().toISOString(),
    },
    // Clearly Filtered Results
    {
        id: '6',
        product_id: '2',
        test_type: 'PFAS',
        status: 'NonDetect',
        result_value: '>99.9% Reduction',
        pdf_url: 'https://cdn.shopify.com/s/files/1/0023/1515/7581/files/Performance_Data_Sheet.pdf',
        tested_at: '2024-01-15',
        lab_name: 'EPA Accredited Lab',
        created_at: new Date().toISOString(),
    },
    {
        id: '7',
        product_id: '2',
        test_type: 'HeavyMetals',
        status: 'Pass',
        result_value: 'Lead >99.9% Removed',
        pdf_url: 'https://cdn.shopify.com/s/files/1/0023/1515/7581/files/Performance_Data_Sheet.pdf',
        tested_at: '2024-01-15',
        lab_name: 'EPA Accredited Lab',
        created_at: new Date().toISOString(),
    },
    {
        id: '8',
        product_id: '2',
        test_type: 'Microplastics',
        status: 'NonDetect',
        result_value: '99.9% Removal',
        pdf_url: 'https://cdn.shopify.com/s/files/1/0023/1515/7581/files/Performance_Data_Sheet.pdf',
        tested_at: '2024-01-15',
        lab_name: 'EPA Accredited Lab',
        created_at: new Date().toISOString(),
    },
    // AquaTru Results
    {
        id: '9',
        product_id: '3',
        test_type: 'PFAS',
        status: 'NonDetect',
        result_value: '98.8% Reduction (PFOA/PFOS)',
        pdf_url: 'https://aquatruwater.com/performance-data-sheet/',
        tested_at: '2023-11-01',
        lab_name: 'IAPMO',
        created_at: new Date().toISOString(),
    },
];

export const mockProducts: Product[] = [
    {
        id: '1',
        brand_id: '1',
        name: 'Essential Prenatal',
        slug: 'essential-prenatal',
        category: 'Prenatal Vitamins',
        image_url: '/products/ritual-prenatal.jpg',
        created_at: new Date().toISOString(),
        brand: mockBrands[0],
        test_results: mockTestResults.slice(0, 5),
        ingredients: [
            mockIngredients[0],
            mockIngredients[1],
            mockIngredients[2],
            mockIngredients[5],
        ],
    },
    {
        id: '2', // Clearly Filtered Pitcher
        brand_id: '5',
        name: 'Water Pitcher with Affinity Filtration',
        slug: 'clearly-filtered-pitcher',
        category: 'Water Filters',
        image_url: '/products/clearly-filtered-pitcher.jpg',
        created_at: new Date().toISOString(),
        brand: mockBrands[4],
        // Note: In a real app we would join this properly. Here we reference the array.
        test_results: [
            // Corresponds to IDs 6, 7, 8
            {
                id: '6',
                product_id: '2',
                test_type: 'PFAS',
                status: 'NonDetect',
                result_value: '>99.9% Reduction',
                pdf_url: 'https://cdn.shopify.com/s/files/1/0023/1515/7581/files/Performance_Data_Sheet.pdf',
                tested_at: '2024-01-15',
                lab_name: 'EPA Accredited Lab',
                created_at: new Date().toISOString(),
            },
            {
                id: '7',
                product_id: '2',
                test_type: 'HeavyMetals',
                status: 'Pass',
                result_value: 'Lead >99.9% Removed',
                pdf_url: 'https://cdn.shopify.com/s/files/1/0023/1515/7581/files/Performance_Data_Sheet.pdf',
                tested_at: '2024-01-15',
                lab_name: 'EPA Accredited Lab',
                created_at: new Date().toISOString(),
            },
            {
                id: '8',
                product_id: '2',
                test_type: 'Microplastics',
                status: 'NonDetect',
                result_value: '99.9% Removal',
                pdf_url: 'https://cdn.shopify.com/s/files/1/0023/1515/7581/files/Performance_Data_Sheet.pdf',
                tested_at: '2024-01-15',
                lab_name: 'EPA Accredited Lab',
                created_at: new Date().toISOString(),
            },
        ],
        ingredients: [mockIngredients[6], mockIngredients[7]],
    },
    {
        id: '3', // AquaTru
        brand_id: '6',
        name: 'AquaTru Classic Countertop RO',
        slug: 'aquatru-classic',
        category: 'Water Filters',
        image_url: '/products/aquatru-classic.jpg',
        created_at: new Date().toISOString(),
        brand: mockBrands[5],
        test_results: [
            {
                id: '9',
                product_id: '3',
                test_type: 'PFAS',
                status: 'NonDetect',
                result_value: '98.8% Reduction (PFOA/PFOS)',
                pdf_url: 'https://aquatruwater.com/performance-data-sheet/',
                tested_at: '2023-11-01',
                lab_name: 'IAPMO',
                created_at: new Date().toISOString(),
            },
        ],
        ingredients: [mockIngredients[6]], // Simplified
    },
    {
        id: '4', // Hydroviv
        brand_id: '7',
        name: 'Hydroviv Under Sink Filter',
        slug: 'hydroviv-under-sink',
        category: 'Water Filters',
        image_url: '/products/hydroviv-under-sink.jpg',
        created_at: new Date().toISOString(),
        brand: mockBrands[6],
        test_results: [], // Proof pending for demo
        ingredients: [mockIngredients[6]],
    },
];

export const categories = [
    'Prenatal Vitamins',
    'Multivitamins',
    'Probiotics',
    'Fish Oil',
    'Protein Powder',
    'Baby Formula',
    'Skincare',
    'Sunscreen',
    'Water Filters',
];
